feat: 🎸 migrate blog settings from remark to contentlayer
abrahamcalsin/abrahamcalsin.com pull request #36
Opened 2022-03-07 21:21 UTC by abrahamcalsin

2022-03-07 21:36 UTC, yonycalsin requested changes

2022-03-07 21:36 UTC, yonycalsin commented on README.md
> +9. https://blog.mrcatdev.com/turns-your-mdx-files-include-yaml-into-data-with-contentlayer-in-nextjs-100daysofcode
I think, these resources should be upload in gists, `https://gist.github.com/`

2022-03-07 21:36 UTC, yonycalsin commented on contentlayer.config.ts
> +  // filePathPattern: `blog/*.md`,
remove this commented line
```suggestion
```

2022-03-07 21:36 UTC, yonycalsin commented on next.config.js
> +  // swcMinify: true,
remove this commented line

```suggestion
```

2022-03-07 21:36 UTC, yonycalsin commented on pages/blog/[slug].tsx
> +  // console.log(123, { params, hasArticle: !!article })
remove this commented line

```suggestion
```

2022-03-08 02:04 UTC, abrahamcalsin commented on README.md
> +9. https://blog.mrcatdev.com/turns-your-mdx-files-include-yaml-into-data-with-contentlayer-in-nextjs-100daysofcode
> I think, these notes should be upload to github-gists like a secret-gist, `https://gist.github.com/`

Okay, thank you, I have just modified it. 🥳

2022-03-08 02:06 UTC, abrahamcalsin commented on contentlayer.config.ts
> +  // filePathPattern: `blog/*.md`,
well, thanks

2022-03-08 02:06 UTC, abrahamcalsin commented on next.config.js
> +  // swcMinify: true,
well, thanks

2022-03-08 02:16 UTC, yonycalsin approved these changes
Good Job 👍

2022-03-08 02:19 UTC, merged