feat: add eslint and workflows
abrahamcalsin/abrahamcalsin.com pull request #43
Opened 2022-05-05 06:18 UTC by abrahamcalsin

2022-05-05 21:18 UTC, yonycalsin requested changes

2022-05-05 21:18 UTC, yonycalsin commented on .github/workflows/main.yml
> +name: Deployment Pipeline
```suggestion
name: Main Pipeline

```

2022-05-05 21:18 UTC, yonycalsin commented on .husky/pre-commit
> +npx lint-staged
you can also use yarn directly, something like that.

```suggestion
yarn lint-staged
```

2022-05-05 21:18 UTC, yonycalsin commented on 6
> +Done in 11.91s.
What is this ? 🤔

2022-05-05 21:18 UTC, yonycalsin commented on README.md
> -``git clone https://github.com/abrahamcalsin/abrahamcalsin.com.git [portfolio-name]``
I think this is not necessary, wdyt ?

2022-05-05 21:18 UTC, yonycalsin commented on README.md
> -``git clone https://github.com/abrahamcalsin/abrahamcalsin.com.git [portfolio-name]``
I'm referring to the cloning guide 😄

2022-05-05 21:18 UTC, yonycalsin commented on package.json
> +    "*.--write": "prettier --write"
What is this for?

```suggestion
```

2022-05-05 21:18 UTC, yonycalsin commented on package.json
> +    "*.{js,jsx,ts,tsx}": "eslint --cache --fix",
you don't need to pass the "cache" option.



https://github.com/yonycalsin/yonycalsin.com/blob/ccb5b36f2605d0b08ca29a6a6cf53428ed00a5cd/package.json#L40-L44

2022-05-05 21:18 UTC, yonycalsin commented on pages/uses/index.tsx
> +    <a href={href} className={'italic !font-bold link-underline'} target="_blank" rel="noopener noreferrer">
```suggestion
    <a href={href} className="italic !font-bold link-underline" target="_blank" rel="noopener noreferrer">
```

2022-05-05 21:18 UTC, yonycalsin commented on src/components/svgs/icons/badge-check-fill-icon/index.tsx
> +export const BadgeCheckFillIcon = () => {
I would recommend you to use functions instead of arrow-functions.

```suggestion
export function BadgeCheckFillIcon() {
```

2022-05-05 21:18 UTC, yonycalsin commented on src/components/title-section/index.tsx
> +import React from 'react'
I recommend you to always import in the following way.



```tsx
import * as React from "react"
```

2022-05-05 21:18 UTC, yonycalsin commented on tailwind.config.js
> +
In objects it is not necessary to have this space.

2022-05-05 22:37 UTC, abrahamcalsin commented on .husky/pre-commit
> +npx lint-staged
of course, thanks 🎉

2022-05-05 22:49 UTC, abrahamcalsin commented on 6
> +Done in 11.91s.
I don't know, I guess mrm or husky generate it. 👀
I will see more on this topic. Anyway lint-staged works correctly without this file.

2022-05-05 22:51 UTC, abrahamcalsin commented on package.json
> +    "*.--write": "prettier --write"
I guess it is for the formatting of the code with prettier 🙄

2022-05-05 22:54 UTC, abrahamcalsin commented on README.md
> -``git clone https://github.com/abrahamcalsin/abrahamcalsin.com.git [portfolio-name]``
hahaha, deleted 😅

2022-05-05 23:00 UTC, abrahamcalsin commented on package.json
> +    "*.{js,jsx,ts,tsx}": "eslint --cache --fix",
ok, thanks 👍

2022-05-05 23:02 UTC, abrahamcalsin commented on pages/uses/index.tsx
> +    <a href={href} className={'italic !font-bold link-underline'} target="_blank" rel="noopener noreferrer">
ohh yeah, I've already changed it, thank you 🎉

2022-05-06 02:14 UTC, abrahamcalsin commented on src/components/svgs/icons/badge-check-fill-icon/index.tsx
> +export const BadgeCheckFillIcon = () => {
thank you, but in which cases should I do it? 🤔

2022-05-06 02:16 UTC, abrahamcalsin commented on src/components/title-section/index.tsx
> +import React from 'react'
Ok, thanks 🎉

2022-05-06 02:17 UTC, abrahamcalsin commented on tailwind.config.js
> +
what do you mean? 🤔

2022-05-06 04:21 UTC, yonycalsin approved these changes

2022-05-06 05:16 UTC, merged